import Head from "next/head";

import NavBar from "@/components/NavBar";
import NavBarMobile from "@/components/NavBarMobile";
import Intro from "@/components/Intro";
import About from "@/components/About";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";

export default function Home() {
  // //COUNTDOWN TO LOAD INTRO
  // const [isVisible, setIsVisible] = useState(false);
  // const loadIntro = () => {
  //   setIsVisible(true);
  // };
  // setTimeout(loadIntro, 4500);

  return (
    <>
      <Head>
        <title>Samuel Santos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <NavBarMobile />
      <Intro />
      <About />
      <Projects/>
      <Contact/>
    </>
  );
}
